"""Convenience re-exports for core workflow data models."""

from .analysis import (
    Analysis,
    AnalysisCollection,
    Condition,
    Contrast,
    Coordinate,
    CoordinateSpace,
    CreateAnalysesResult,
    Image,
)
from .download import DownloadResult, DownloadSource, DownloadedFile, FileType
from .extract import ArticleExtractionBundle, ExtractedContent, ExtractedTable
from .export_dir import (
    AnalysisFile,
    ArticleDataFile,
    ArticleDirectory,
    ArticleMetadataFile,
    BinaryFile,
    ExtractorSourceTree,
    IdentifierFile,
    JsonFile,
    JsonLinesFile,
    ProcessedExtractorTree,
    TablesIndexFile,
    TextFile,
)
from .ids import Identifier, IdentifierExpansion, Identifiers
from .metadata import (
    ArticleMetadata,
    Author,
    merge_metadata_from_sources,
)
from .cache import (
    CACHE_SCHEMA_VERSION,
    CacheEnvelope,
    CacheIndex,
    CreateAnalysesResultEntry,
    CreateAnalysesResultIndex,
    DownloadCacheEntry,
    DownloadIndex,
    ExtractionResultEntry,
    ExtractionResultIndex,
    IdentifierCacheEntry,
    IdentifierCacheIndex,
    MetadataCache,
    MetadataCacheIndex,
    UploadCacheEntry,
    UploadCacheIndex,
)
from .upload import (
    BaseStudyPayload,
    StudyPayload,
    TablePayload,
    UploadOutcome,
    UploadWorkItem,
    PreparedAnalysis,
)

# Align with earlier interface expectations.
ExtractionResult = ExtractedContent
ExtractionIndex = ExtractionResultIndex

__all__ = [
    "Analysis",
    "AnalysisFile",
    "ArticleDataFile",
    "ArticleDirectory",
    "AnalysisCollection",
    "ArticleExtractionBundle",
    "ArticleMetadata",
    "Author",
    "ArticleMetadataFile",
    "CACHE_SCHEMA_VERSION",
    "CacheEnvelope",
    "CacheIndex",
    "Condition",
    "Contrast",
    "Coordinate",
    "CoordinateSpace",
    "CreateAnalysesResult",
    "CreateAnalysesResultEntry",
    "CreateAnalysesResultIndex",
    "DownloadCacheEntry",
    "DownloadIndex",
    "DownloadResult",
    "DownloadSource",
    "DownloadedFile",
    "ExtractionIndex",
    "ExtractionResult",
    "ExtractedContent",
    "ExtractedTable",
    "ExtractionResultEntry",
    "ExtractionResultIndex",
    "BinaryFile",
    "FileType",
    "Identifier",
    "IdentifierExpansion",
    "Identifiers",
    "IdentifierCacheEntry",
    "IdentifierCacheIndex",
    "Image",
    "ExtractorSourceTree",
    "IdentifierFile",
    "JsonFile",
    "JsonLinesFile",
    "MetadataCache",
    "MetadataCacheIndex",
    "ProcessedExtractorTree",
    "TablesIndexFile",
    "TextFile",
    "merge_metadata_from_sources",
    "BaseStudyPayload",
    "StudyPayload",
    "TablePayload",
    "UploadOutcome",
    "UploadWorkItem",
    "PreparedAnalysis",
    "UploadCacheEntry",
    "UploadCacheIndex",
]
